nelmio_api_doc:
  documentation:
    info:
      title: Dviračių parduotuvė
      description:
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/login_check$)(?!/doc$)